
author:
    - name: Theramesh Hay
      email: hayt2@vcu.com

date: last-modified

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
